name: 自動ビルド(Gradle)

on:
  push:
    branches:
     - develop
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Setup Gradle 8.11.1
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.11.1
    - name: Build with Gradle 8.11.1
      run: gradlew build
    - name: Report build results
      uses: gmazzo/publish-report-annotations@v1 # target latest major
      if: ${{ !cancelled() }}
    - name: Upload War File
      uses: actions/upload-artifact@v4
      with:
        name: prototypePh2
        path: build/libs/*.war