name: CheckStyle for Java on Reviewdog

on:
  issue_comment:
    types:
      - created

permissions:
 contents: read
 pull-requests: write

jobs:
  java-checkstyle-check:
    # add comment of pull request && comment is KEYWORD
    if: (github.event.issue.pull_request != null) && github.event.comment.body == '!run checkstyle'  
    runs-on: ubuntu-latest
    steps:
      - name: Get Target Branch
        uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
    
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.set-target-branch.outputs.result }}

      - name: Super-linter
        uses: super-linter/super-linter/slim@v7.2.1 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true # 新規・変更分のみを対象とする場合はfalseに変更
          DISABLE_ERRORS: true
          VALIDATE_JAVA: true
          VALIDATE_XML: true
          JAVA_FILE_NAME: google_checks.xml
          LOG_LEVEL: INFO # 詳細を確認する場合はDEBUGへ変更
          SAVE_SUPER_LINTER_OUTPUT: true
